### ISSUE TITLE
Jesse TODO

### ISSUE THREAD

**Issue by JesseNoseworthy** [JesseNoseworthy/wpSingle#2]
Tasks prior to development
- [ ] Organize design (https://github.com/JesseNoseworthy/wpSingle/issues/3)
- [ ] Remove redundant and unused files/syntax/components from previous site
- [ ] organize WP plugins
- [ ] Establish compiler
- [ ] Resolve hosting issues
